/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#e9c349',
        'on-secondary': '#3d2e00',
        'on-primary-container': '#554300',
        'primary-fixed-dim': '#e9c349',
        'on-surface-variant': '#d0c5af',
        'surface-container-highest': '#353534',
        'on-secondary-fixed-variant': '#584400',
        'surface-dim': '#131313',
        'secondary-container': '#d2a501',
        'surface': '#131313',
        'surface-container-high': '#2a2a2a',
        'secondary-fixed': '#ffdf90',
        'secondary': '#f0c12c',
        'on-secondary-container': '#503d00',
        'tertiary': '#d0cdcd',
        'background': '#131313',
        'surface-container-lowest': '#0e0e0e',
        'on-primary': '#3c2f00',
        'inverse-surface': '#e5e2e1',
        'error-container': '#93000a',
        'outline': '#99907c',
        'on-secondary-fixed': '#241a00',
        'error': '#ffb4ab',
        'inverse-on-surface': '#313030',
        'on-tertiary': '#313030',
        'on-tertiary-fixed-variant': '#474746',
        'surface-container-low': '#1c1b1b',
        'on-background': '#e5e2e1',
        'on-error': '#690005',
        'primary-fixed': '#ffe088',
        'outline-variant': '#4d4635',
        'on-primary-fixed-variant': '#574500',
        'on-surface': '#e5e2e1',
        'on-tertiary-container': '#454544',
        'secondary-fixed-dim': '#f0c12c',
        'tertiary-fixed-dim': '#c8c6c5',
        'surface-container': '#201f1f',
        'tertiary-container': '#b4b2b2',
        'on-tertiary-fixed': '#1c1b1b',
        'primary-container': '#d4af37',
        'on-error-container': '#ffdad6',
        'on-primary-fixed': '#241a00',
        'tertiary-fixed': '#e5e2e1',
        'surface-bright': '#393939',
        'inverse-primary': '#735c00',
        'primary': '#f2ca50',
        'surface-variant': '#353534',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      spacing: {
        'margin-mobile': '20px',
        'unit': '8px',
        'container-max': '1200px',
        'margin-desktop': '64px',
        'gutter': '24px',
      },
      fontFamily: {
        'display': ['Playfair Display', 'serif'],
        'headline': ['Playfair Display', 'serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.03em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
